name: Flutter CI/CD

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.1"
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build APK (auto version bump)
        run: |
          # Extract base version (everything before '+')
          VERSION_NAME=$(grep '^version:' pubspec.yaml | sed 's/version: \(.*\)+.*/\1/')

          # Use GitHub run number as build number
          BUILD_NUMBER=${{ github.run_number }}

          echo "Building version $VERSION_NAME+$BUILD_NUMBER"

          # Update pubspec.yaml temporarily for this build
          sed -i "s/^version: .*/version: $VERSION_NAME+$BUILD_NUMBER/" pubspec.yaml

          flutter build apk --release --build-name=$VERSION_NAME --build-number=$BUILD_NUMBER

      - name: Upload build artifact (APK)
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download built APK
        uses: actions/download-artifact@v4
        with:
          name: release-apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
